### ISSUE TITLE
fetchBot is failing - profiles aren't getting refreshed

### ISSUE THREAD

**Issue by AurelienLourot** [AurelienLourot/ghuser.io#124]
```
⠦ Fetching omegaup/omegaup's contributors...Promise {
  <rejected> TypeError: Cannot read property 'login' of null
    at fetchRepoContributors (/home/ubuntu/ghuser.io/db/fetchRepos.js:223:57)
    at process._tickCallback (internal/process/next_tick.js:68:7) }
/home/ubuntu/ghuser.io/db/impl/scriptUtils.js:9
      throw e;
      ^

TypeError: Cannot read property 'login' of null
    at fetchRepoContributors (/home/ubuntu/ghuser.io/db/fetchRepos.js:223:57)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by AurelienLourot** [comment]
Vanished, closing for now.
